#!/bin/bash
#
# Local CI/CD Build Script
# Replicates the GitHub Actions CI/CD pipeline locally for testing before commit
#
# Usage:
#   ./scripts/local-ci-build.sh [options]
#
# Options:
#   --skip-build    Skip APK build (faster for quick testing)
#   --skip-tests    Skip running tests
#   --clean         Run flutter clean first
#

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Parse arguments
SKIP_BUILD=false
SKIP_TESTS=false
CLEAN_FIRST=false

for arg in "$@"; do
  case $arg in
    --skip-build)
      SKIP_BUILD=true
      shift
      ;;
    --skip-tests)
      SKIP_TESTS=true
      shift
      ;;
    --clean)
      CLEAN_FIRST=true
      shift
      ;;
    --help|-h)
      echo "Usage: $0 [options]"
      echo ""
      echo "Options:"
      echo "  --skip-build    Skip APK build (faster for quick testing)"
      echo "  --skip-tests    Skip running tests"
      echo "  --clean         Run flutter clean first"
      echo "  --help, -h      Show this help message"
      exit 0
      ;;
  esac
done

# Print header
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Local CI/CD Build Test${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Step 0: Clean (optional)
if [ "$CLEAN_FIRST" = true ]; then
  echo -e "${YELLOW}[0/9] Cleaning build artifacts...${NC}"
  flutter clean
  echo -e "${GREEN}✓ Clean complete${NC}"
  echo ""
fi

# Step 1: Generate build_info.dart (same as CI/CD)
echo -e "${YELLOW}[1/9] Generating build_info.dart...${NC}"
mkdir -p lib/config
GIT_COMMIT_HASH=$(git rev-parse HEAD)
GIT_COMMIT_SHORT=$(git rev-parse --short HEAD)
BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > lib/config/build_info.dart <<EOF
/// Build information generated at build time.
/// This file is auto-generated by the CI/CD pipeline.
/// DO NOT EDIT THIS FILE MANUALLY.
class BuildInfo {
  /// Full Git commit hash
  static const String gitCommitHash = '$GIT_COMMIT_HASH';

  /// Short Git commit hash (first 7 characters)
  static const String gitCommitShort = '$GIT_COMMIT_SHORT';

  /// Build timestamp in ISO 8601 format
  static const String buildTimestamp = '$BUILD_TIMESTAMP';
}
EOF

echo -e "${GREEN}✓ Generated build_info.dart${NC}"
echo "  Commit: $GIT_COMMIT_SHORT"
echo "  Timestamp: $BUILD_TIMESTAMP"
echo ""

# Step 2: Verify Flutter installation
echo -e "${YELLOW}[2/9] Verifying Flutter installation...${NC}"
flutter --version | head -n 1
echo -e "${GREEN}✓ Flutter verified${NC}"
echo ""

# Step 3: Get dependencies
echo -e "${YELLOW}[3/9] Getting Flutter dependencies...${NC}"
flutter pub get > /dev/null
echo -e "${GREEN}✓ Dependencies installed${NC}"
echo ""

# Step 4: Run Flutter analyzer
echo -e "${YELLOW}[4/9] Running Flutter analyzer...${NC}"
if flutter analyze --no-fatal-infos 2>&1 | tee /tmp/flutter-analyze.log; then
  echo -e "${GREEN}✓ Analyzer passed${NC}"
else
  ERROR_COUNT=$(grep -c "error •" /tmp/flutter-analyze.log || echo "0")
  WARNING_COUNT=$(grep -c "warning •" /tmp/flutter-analyze.log || echo "0")
  INFO_COUNT=$(grep -c "info •" /tmp/flutter-analyze.log || echo "0")

  echo -e "${YELLOW}⚠ Analyzer found issues:${NC}"
  echo "  - Errors: $ERROR_COUNT"
  echo "  - Warnings: $WARNING_COUNT"
  echo "  - Info: $INFO_COUNT"
  echo ""
  echo -e "${BLUE}Note: CI/CD continues on analyzer warnings (continue-on-error: true)${NC}"
fi
echo ""

if [ "$SKIP_TESTS" = false ]; then
  # Step 5: Run Flutter tests with coverage
  echo -e "${YELLOW}[5/9] Running Flutter tests with coverage...${NC}"
  if flutter test --coverage 2>&1; then
    echo -e "${GREEN}✓ Tests passed${NC}"

    # Generate coverage summary (if lcov is available)
    if command -v lcov &> /dev/null && [ -f coverage/lcov.info ]; then
      COVERAGE=$(lcov --summary coverage/lcov.info 2>&1 | grep -oP 'lines......: \K[0-9.]+(?=%)' || echo "0")
      echo "  Coverage: ${COVERAGE}% (target: 70%)"
      if (( $(echo "$COVERAGE >= 70" | bc -l 2>/dev/null || echo "0") )); then
        echo -e "${GREEN}  ✓ Meets coverage target${NC}"
      else
        echo -e "${YELLOW}  ⚠ Below coverage target${NC}"
      fi
    fi
  else
    echo -e "${YELLOW}⚠ Tests had failures${NC}"
    echo -e "${BLUE}Note: CI/CD continues on test failures (continue-on-error: true)${NC}"
  fi
  echo ""

  # Step 6: Run schema validation test (CRITICAL)
  echo -e "${YELLOW}[6/9] Running schema validation test (CRITICAL)...${NC}"
  if flutter test test/schema_validation_test.dart; then
    echo -e "${GREEN}✓ Schema validation passed${NC}"
  else
    echo -e "${RED}✗ Schema validation FAILED${NC}"
    echo -e "${RED}This would FAIL the CI/CD build!${NC}"
    exit 1
  fi
  echo ""

  # Step 7: Run provider tests (CRITICAL)
  echo -e "${YELLOW}[7/9] Running provider tests (CRITICAL)...${NC}"
  if flutter test test/providers/; then
    echo -e "${GREEN}✓ Provider tests passed${NC}"
  else
    echo -e "${RED}✗ Provider tests FAILED${NC}"
    echo -e "${RED}This would FAIL the CI/CD build!${NC}"
    exit 1
  fi
  echo ""
else
  echo -e "${BLUE}[5-7/9] Skipping tests (--skip-tests flag)${NC}"
  echo ""
fi

if [ "$SKIP_BUILD" = false ]; then
  # Step 8: Build debug APK
  echo -e "${YELLOW}[8/9] Building debug APK...${NC}"
  if flutter build apk --debug --split-per-abi; then
    echo -e "${GREEN}✓ Debug APK built successfully${NC}"
    ls -lh build/app/outputs/flutter-apk/*-debug.apk | awk '{print "  " $9 " (" $5 ")"}'
  else
    echo -e "${RED}✗ Debug APK build FAILED${NC}"
    exit 1
  fi
  echo ""

  # Step 9: Build release APK
  echo -e "${YELLOW}[9/9] Building release APK...${NC}"
  if flutter build apk --release --split-per-abi --shrink; then
    echo -e "${GREEN}✓ Release APK built successfully${NC}"
    ls -lh build/app/outputs/flutter-apk/*-release.apk | awk '{print "  " $9 " (" $5 ")"}'
  else
    echo -e "${RED}✗ Release APK build FAILED${NC}"
    exit 1
  fi
  echo ""
else
  echo -e "${BLUE}[8-9/9] Skipping APK build (--skip-build flag)${NC}"
  echo ""
fi

# Summary
echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}  ✓ Local CI/CD build complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Your changes are ready to commit and should pass CI/CD."
echo ""
echo -e "${YELLOW}Note: Remember to add lib/config/build_info.dart to .gitignore${NC}"
echo "      (This file should only exist locally for testing)"
echo ""

# Cleanup option
echo -e "${BLUE}Clean up build_info.dart?${NC}"
echo "  To keep:   (allows running app with build info)"
echo "  To remove: rm lib/config/build_info.dart"
echo ""
